### ISSUE TITLE
High Score?

### ISSUE THREAD

**Issue by jggames** [Fabrizio-Caruso/TRS-80-BASIC-10-liners#1]
0 CLS0:A=16384:O=A+95:P=A+271:M=35:K=1:FORI=0TOM:POKEO+RND(384),M:NEXT:PRINT@0,"USE IJKL <SPC>":R=R*-(J<R)+J*-(J>R)
1 B=49151:Q=.98:G=O-95:H=106:W=100:V=3:T=32:Z=64:N=160:D=A+480:J=.:PRINT@20,"HI:"R;:FORI=.TO1STEPR:I=-(INKEY$<>""):NEXT
2 POKEA+45,13:POKEA+46,9:POKEA+47,14:POKEA+48,5:POKEA+49,19:POKEA+50,43:FORI=0TO31:POKEO-I,255-T:POKED+I,255-T:NEXT
3 PRINT@0,"$"9-F;"  "V" SCORE:"J" HI:"R:POKEO-90,H:IFPEEK(P)=WTHENSOUNDZ,1:J=J+9:F=F+(F>.)
4 POKEP,255-Z:IFRND(.)>QANDP>O+TTHENX=P-6+2*RND(5)-Z*(RND(3)-2):POKEX,M
5 L=JAND3:A$=INKEY$:S=.:Y=.:IFA$<>""THENS=ASC(A$):E=SAND1:Q=Q-.0005
6 C=S-75+E:POKEP,H:IFSGN(C)=CTHENY=1:POKEP,M:P=P+C*31*E+C:J=J+1:SOUNDT,1:IFJ>=K*500THENPOKEB,Z:K=K+1:F=0:V=V-(V<9)
7 V=-V*(P<D ANDP>O):POKEG,W:G=O-95:POKEB,0:IF-YTHENIFL=3THENG=O+RND(384):POKEG,36
8 IFS=TTHENIFF<9THENPOKEB,Z:POKEP-1,N:POKEP+1,N:POKEP-T,N:POKEP+T,N:F=F+1:POKEP,106-Z:IFP>=(D-T)ORP<=(O+T)GOTO2
9 ON-(V>0AND(PEEK(P)<>M))GOTO3:F=.:POKEP,H:V=V-1:SOUND1,2:ON-(V>0)GOTO3:?@T,"hit€C";:FORI=0TO1STEP0:I=-(INKEY$="C"):NEXT:GOTO0

Just a few ideas for tweaks, take or leave as you please.

I added a high score routine in line 0.  And also a hit C (to continue) routine in line 9. Just in case someone wants to look a their screen after they die.  Also made it so the hit a key routine in line 1 is disabled after the first game played.  That way you can just hit C and immediately begin playing a new game after each death.

**Comment by Fabrizio-ASTEK** [comment]
Thanks!
I will fix the record and do something about the continuation.
I will probably have to rewrite from scratch this game to make it fit into a PUR-80 but as a PUR-120 I will just fix the record and implement some continuation with a key-press.

R=R*-(J<R)+J*-(J>R) = 0 for R=J, 
R=R*-(J<R)+J*-(J>=R) is probably correct as well as
IFJ>R THENR=J which saves some characters and is ok because it is at the end of the line.
I would use Boolean expressions to avoid IFs when I cannot place them at the end.

**Comment by Fabrizio-Caruso** [comment]
The record issue is now fixed.
I have also added a wait to press a key and an extra sound for each new extra life (every 500 points).
